/**
 * Node-jst for browsers
 * Copyright(c) 2011 Shaun Li <me@shaunli.com>
 * MIT Licensed
 *
 * Generated by bin/build-browser -- edit lib/ instead.
 */

;(function(root) {

  var defs = {}, cache = {};

  function require(name) {
    if (!cache[name]) {
      var module = {exports: {}};
      cache[name] = module.exports;
      defs[name](module.exports, module, require);
      cache[name] = module.exports;
    }
    return cache[name];
  }

  defs['./errors'] = function(exports, module, require) {
    /**
     * Compiler diagnostics.
     *
     * A template that will not compile used to report whatever V8 said about the
     * generated code -- "Unexpected token 'return'" -- with no hint of which
     * template, let alone which line, was at fault.
     */

    function position(ctx, index) {
      var line = 1, start = 0;

      for (var i = 0; i < index; i++) {
        if (ctx.charCodeAt(i) === 10) { line++; start = i + 1; }
      }

      return {line: line, column: index - start + 1};
    }

    // Three lines of context with a caret under the offending column.
    function excerpt(ctx, pos) {
      var lines = ctx.split('\n'),
          width = String(Math.min(lines.length, pos.line + 1)).length,
          out = [];

      for (var n = Math.max(1, pos.line - 2); n <= Math.min(lines.length, pos.line + 1); n++) {
        var num = String(n).padStart(width);

        out.push('  ' + num + ' | ' + lines[n - 1]);

        if (n === pos.line)
          out.push('  ' + ' '.repeat(width) + ' | ' + ' '.repeat(pos.column - 1) + '^');
      }

      return out.join('\n');
    }

    exports.at = function(message, ctx, index, name) {
      var pos = position(ctx, index),
          err = new Error('jst: ' + message + '\n  at ' + (name || '<template>')
            + ':' + pos.line + ':' + pos.column + '\n\n' + excerpt(ctx, pos) + '\n');

      err.fileName = name;
      err.line = pos.line;
      err.column = pos.column;

      return err;
    }

    // Last resort: the generated code did not parse and nothing in the template
    // looked obviously wrong, so show what was generated.
    exports.generated = function(cause, code, name) {
      var lines = code.split('\n'),
          shown = lines.slice(0, 40).map(function(line, i) {
            if (line.length > 120) line = line.substring(0, 117) + '...';
            return '  ' + String(i + 1).padStart(3) + ' | ' + line;
          });

      if (lines.length > 40) shown.push('      | ... ' + (lines.length - 40) + ' more lines');

      var err = new Error('jst: could not compile ' + (name || '<template>') + '\n  '
        + cause.message + '\n\nGenerated code:\n' + shown.join('\n') + '\n');

      err.fileName = name;
      err.cause = cause;

      return err;
    }

    /**
     * Points at the tag that most likely broke a compile. Only ever called once
     * the compile has already failed, so a false positive costs nothing and
     * regex literals, comments and division do not have to be told apart
     * perfectly.
     */
    exports.blame = function(tags) {
      for (var i = 0; i < tags.length; i++) {
        var reason = unbalanced(tags[i].src, tags[i].braces);
        if (reason) return {index: tags[i].index, reason: reason};
      }
      return null;
    }

    // Braces legitimately span tags -- {% if (x) { %} opens one that {% } %}
    // closes -- so they are only checked inside a {{ }} expression.
    function unbalanced(src, braces) {
      var stack = [], quote = null,
          opens = {')': '(', ']': '[', '}': '{'};

      for (var i = 0; i < src.length; i++) {
        var ch = src[i];

        if (quote) {
          if (ch === '\\') i++;
          else if (ch === quote) quote = null;
          continue;
        }

        if (ch === '/' && src[i + 1] === '/') return null;   // a comment; give up
        if (ch === '/' && src[i + 1] === '*') return null;
        if (ch === '/') return null;                          // regex or division

        if (ch === '"' || ch === "'" || ch === '`') quote = ch;
        else if (ch === '(' || ch === '[' || (braces && ch === '{')) stack.push(ch);
        else if (ch === ')' || ch === ']' || (braces && ch === '}')) {
          if (stack.pop() !== opens[ch]) return 'unbalanced "' + ch + '"';
        }
      }

      if (quote) return 'unterminated ' + quote + quote + ' string';
      if (stack.length) return 'unbalanced "' + stack[stack.length - 1] + '"';

      return null;
    }

  };

  defs['./scope'] = function(exports, module, require) {
    /**
     * Decides whether compiled code needs a `with(it)` block.
     *
     * `with` costs 3-30x at render time, so it is worth skipping when every
     * identifier a template touches is either declared by the template itself,
     * a language keyword, a well-known global, or already `it.`-prefixed.
     *
     * Every ambiguity resolves towards `true` (keep `with`): a wrong `true` is
     * only slow, a wrong `false` would break the template.
     */

    // Tokens we care about: comments and strings are skipped wholesale, `.foo`
    // member access is captured so it is not mistaken for a free identifier.
    const tokenre = /\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:[^"\\\n]|\\[\s\S])*"|'(?:[^'\\\n]|\\[\s\S])*'|`(?:[^`\\]|\\[\s\S])*`|(\.\s*)?([A-Za-z_$][\w$]*)|[\s\S]/g,
          keywords = new Set(('var let const function return if else for while do switch case break '
            + 'continue new typeof instanceof in of delete void this null true false undefined '
            + 'try catch finally throw class extends super yield await default with debugger').split(' ')),
          // Built-ins nobody puts on a template context.
          globals = new Set(('Math JSON Date console Number String Array Object Boolean RegExp Error '
            + 'parseInt parseFloat isNaN isFinite NaN Infinity encodeURIComponent decodeURIComponent '
            + 'encodeURI decodeURI Map Set Promise Symbol').split(' ')),
          // Names the generated function provides itself.
          provided = new Set(['it', 'filters', 'out']),
          // Positions after which a `{` opens an object literal rather than a block.
          objectPos = new Set(['(', ',', '=', ':', '[', '?', 'return', '']),
          colonre = /^\s*:/;

    exports.needsWith = function(code) {
      var m, declared = new Set(),
          // Declaration state: inside `var a = 1, b = 2` we alternate between
          // expecting a name and reading an initialiser expression.
          declMode = false, expectName = false, depth = 0,
          // `function f(a, b)` / `catch (e)`: every name up to the closing paren
          // is a binding, not a free variable.
          paramMode = 0, paramDepth = 0,
          // Brace kinds, so `{key: v}` keys are not mistaken for variables while
          // `a ? b : c` still is.
          braces = [], prev = '',
          free = [];

      tokenre.lastIndex = 0;

      while ((m = tokenre.exec(code)) !== null) {
        var name = m[2];

        if (name === undefined) {
          var ch = m[0];
          if (ch.trim() === '') continue;
          if (ch === '(' || ch === '[' || ch === '{') {
            if (ch === '{') braces.push(objectPos.has(prev) ? 'obj' : 'block');
            depth++;
            if (paramMode === 1 && ch === '(') { paramMode = 2; paramDepth = depth; }
          } else if (ch === ')' || ch === ']' || ch === '}') {
            if (ch === '}') braces.pop();
            if (paramMode === 2 && depth === paramDepth) paramMode = 0;
            depth--;
            if (depth <= 0) { depth = 0; if (declMode) declMode = expectName = false; }
          } else if (ch === ',') {
            if (declMode && depth === 0) expectName = true;
          } else if (ch === ';') {
            declMode = false; expectName = false;
          }
          prev = ch;
          continue;
        }

        prev = name;

        if (m[1]) continue;                   // `.foo` — a property, not a variable

        if (paramMode === 2) { declared.add(name); continue; }

        if (name === 'function' || name === 'catch') { paramMode = 1; continue; }

        if (name === 'var' || name === 'let' || name === 'const') {
          declMode = true; expectName = true; depth = 0;
          continue;
        }

        if (declMode && expectName && depth === 0) {
          declared.add(name);
          expectName = false;
          continue;
        }

        if (paramMode === 1) { declared.add(name); continue; }   // function name

        if (braces[braces.length - 1] === 'obj' && colonre.test(code.slice(tokenre.lastIndex)))
          continue;                           // object literal key

        if (keywords.has(name) || globals.has(name) || provided.has(name)
            || declared.has(name)) continue;

        free.push(name);
      }

      return free.length > 0;
    }

    const filterre = /^\s*[A-Za-z_$][\w$]*\s*(?:\(([\s\S]*)\))?\s*$/;

    /**
     * Given the parts of a `{{ expr|filter|filter(arg) }}` body, keeps only the
     * code whose identifiers really come from the context: the expression itself
     * and any filter arguments, but not the filter names.
     */
    exports.expression = function(parts) {
      return parts.reduce(function(code, part) {
        var m = filterre.exec(part);
        return code + '\n' + (m ? (m[1] || '') : part);
      });
    }

  };

  defs['./filters'] = function(exports, module, require) {
    // filters

    const htmlCodes = {'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'},
          htmlre = /&(?!\w+;)|<|>|"|'/g,
          htmlEscape = function (src) { return htmlCodes[src]; },
          // Most strings need no escaping at all; one cheap scan beats building a
          // replacement for them.
          htmltestre = /[&<>"']/,
          linere = /(\r\n|\r|\n)/g,
          breakre = /\r\n|\r|\n/g,
          // A filter is a name, optionally called with arguments.
          filterre = /^[A-Za-z_$][\w$]*(?:\([\s\S]*\))?$/;

    /**
     * Splits `expr|filter|filter(arg)` on the filter separator. A `|` inside a
     * string or a nested call belongs to the expression, and `||` is the logical
     * operator rather than two empty filters.
     */
    exports.split = function(src) {
      var parts = [], start = 0, depth = 0, quote = null;

      for (var i = 0; i < src.length; i++) {
        var ch = src[i];

        if (quote) {
          if (ch === '\\') i++;
          else if (ch === quote) quote = null;
          continue;
        }

        if (ch === '"' || ch === "'" || ch === '`') quote = ch;
        else if (ch === '(' || ch === '[' || ch === '{') depth++;
        else if (ch === ')' || ch === ']' || ch === '}') depth--;
        else if (ch === '|' && depth === 0) {
          if (src[i + 1] === '|') { i++; continue; }

          parts.push(src.substring(start, i));
          start = i + 1;
        }
      }

      parts.push(src.substring(start));

      return parts;
    }

    exports.convert = function(parts) {
      return parts.reduce(function(code, filter) {
        filter = filter.trim();

        if (!filterre.test(filter))
          throw new Error('`' + filter + '` is not a filter name');

        return 'filters.' + filter + '(' + code + ')';
      });
    }

    function escape(src) {
      if (typeof src !== 'string' || !htmltestre.test(src)) return src;
      return src.replace(htmlre, htmlEscape);
    }

    function linebreaks(src) {
      if (typeof src !== 'string') return src;
      return '<p>' + src.split(breakre).join('</p><p>') + '</p>';
    }

    function linebreaksbr(src) {
      if (typeof src !== 'string') return src;
      return src.replace(linere, '<br>$1');
    }

    function add(value) {
      return function(src) { return Number(value) + Number(src); };
    }

    exports.filters = {
      escape: escape, e: escape,
      linebreaks: linebreaks,
      linebreaksbr: linebreaksbr,
      add: add
    };

  };

  defs['./compiler'] = function(exports, module, require) {
    /**
     * Node-jst compiler
     * Copyright(c) 2011 Shaun Li <me@shaunli.com>
     * MIT Licensed
     *
     * Platform-independent: no fs, no path. lib/jst.js adds file rendering on top
     * and bin/build-browser bundles this file for the browser.
     */

    var filters = require('./filters'),
        scope = require('./scope'),
        errors = require('./errors');

    exports.filters = filters.filters;

    exports.addFilter = function(name, fn) {
      filters.filters[name] = fn;
    }

    exports.addFilters = function(newFilters) {
      for (var name in newFilters)
        filters.filters[name] = newFilters[name];
    }

    var _cache = Object.create(null);

    // compiler

    const prefixes = {
            n: {s: '"', c: '""; ', v: '"" + '},
            s: {s: '', c: '"; ', v: '" + '},
            c: {s: ' out += "', c: ' ', v: ' out += '},
            v: {s: ' + "', c: '; ', v: ' + '},
            end: {n: '""; ', s: '"; ', c: ' ', v: '; '}
          },
          tokenre = /\{#[\s\S]*?#\}|\{%\s([\s\S]+?)\s%\}|\{\{\s([\s\S]+?)\s\}\}/g,
          textcodes = {'\\': '\\\\', '"': '\\"', '\n': '\\n', '\r': '\\r', '\t': '\\t',
            '\u2028': '\\u2028', '\u2029': '\\u2029'},
          textre = /[\\"\n\r\t\u2028\u2029]/g,
          textEscape = function(src) { return textcodes[src]; },
          // <pre> and <textarea> content is significant and must survive minifying.
          rawre = /<(\/?)(?:pre|textarea)\b/gi,
          wsre = /[\t\r\n]/g,
          // A `{{` or `{%` left in the text means a tag was written without the
          // spaces the syntax requires, and would otherwise reach the page as-is.
          strayre = /\{\{|\{%/;

    // Collapses layout whitespace, but leaves anything inside <pre>/<textarea>
    // alone. `state.raw` carries the nesting depth across text segments.
    function minify(text, state) {
      var m, out = '', i = 0;

      rawre.lastIndex = 0;

      while ((m = rawre.exec(text)) !== null) {
        out += strip(text.substring(i, m.index), state) + m[0];
        if (m[1]) { if (state.raw > 0) state.raw--; } else state.raw++;
        i = m.index + m[0].length;
      }

      return out + strip(text.substring(i), state);
    }

    function strip(text, state) {
      return state.raw > 0 ? text : text.replace(wsre, '');
    }

    var compile = exports.compile = function(ctx, isToCode, name) {
      var m, i = 0,
          state = {raw: 0},
          // Segments are collected first because whether the code needs a
          // `with(it)` block decides how the very first one is emitted.
          segs = [],
          // Tag sources, kept so a failed compile can say which tag broke it.
          tags = [],
          script = '';

      function text(src, offset) {
        var stray = strayre.exec(src);

        if (stray)
          throw errors.at('unexpected `' + stray[0] + '` -- a tag needs spaces '
            + 'inside it, as `{{ name }}` or `{% code %}`. For a literal, write '
            + '`{{ \'' + stray[0] + '\' }}`', ctx, offset + stray.index, name);

        src = minify(src, state);
        if (src !== '') segs.push({s: src.replace(textre, textEscape)});
      }

      tokenre.lastIndex = 0;

      while ((m = tokenre.exec(ctx)) !== null) {
        if (m.index > i) text(ctx.substring(i, m.index), i);

        if (m[1] !== undefined) {
          // `{% code %}` — newlines around it keep a trailing `//` comment from
          // swallowing the statements the compiler appends.
          segs.push({c: '\n' + m[1] + (/\)$/.test(m[1]) ? ';' : '') + '\n'});
          script += m[1] + '\n';
          tags.push({index: m.index, src: m[1], braces: false});
        } else if (m[2] !== undefined) {
          var parts = filters.split(m[2]);

          try {
            // Parenthesised: the value is concatenated into a larger expression,
            // and `||`, `?:` and friends bind looser than `+`.
            segs.push({v: '(' + filters.convert(parts) + ')'});
          } catch (e) {
            throw errors.at(e.message, ctx, m.index, name);
          }

          script += scope.expression(parts) + '\n';
          tags.push({index: m.index, src: m[2], braces: true});
        }
        // `{# comment #}` falls through, emitting nothing.

        i = m.index + m[0].length;
      }

      if (i < ctx.length) text(ctx.substring(i), i);

      var useWith = scope.needsWith(script),
          last = useWith ? 'c' : 'n',
          body = '';

      for (i = 0; i < segs.length; i++) {
        var kind = segs[i].s !== undefined ? 's' : segs[i].c !== undefined ? 'c' : 'v';
        body += prefixes[last][kind] + segs[i][kind];
        last = kind;
      }

      body += prefixes['end'][last];

      var code = 'var out = ' + (useWith ? '""; with(it) {' + body + '} ' : body) + 'return out;';

      // `filters` is closed over rather than passed in, so the compiled function
      // takes a single argument and needs no call-time forwarding.
      var source = isToCode
        ? 'function(it) { it = it || {}; var filters = jst.filters;' + code + '}'
        : 'return function(it) { it = it || {};' + code + '}';

      try {
        var fn = new Function('filters', isToCode ? 'return ' + source : source);
        return isToCode ? source : fn(filters.filters);
      } catch (e) {
        // The generated code did not parse. Point at the tag responsible if one
        // stands out, and fall back to showing what was generated.
        var blamed = errors.blame(tags);

        throw blamed
          ? errors.at(blamed.reason + ' in this tag', ctx, blamed.index, name)
          : errors.generated(e, source, name);
      }
    }

    var render = exports.render = function(ctx, args) {
      var fn = _cache[ctx];

      if (fn === undefined) {
        fn = _cache[ctx] = compile(ctx);
      }

      return fn(args);
    }


  };

  var jst = require('./compiler');

  if (typeof module !== 'undefined' && module.exports) module.exports = jst;
  else if (typeof define === 'function' && define.amd) define(function() { return jst; });
  else root.jst = jst;

})(typeof self !== 'undefined' ? self : this);
